
drop table if exists category cascade;
create table category (id bigserial, name varchar(255), primary key(id));
insert into category (name) values ('Alcoholic drinks');
insert into category (name) values ('Soft drinks');
insert into category (name) values ('Milk products');
insert into category (name) values ('Flour products');
insert into category (name) values ('Vegetables');
insert into category (name) values ('Condiments');
insert into category (name) values ('Kitchen goods');
insert into category (name) values ('Berries and fruits');
insert into category (name) values ('Clothes and accessories');
insert into category (name) values ('Meat and fish');
insert into category (name) values ('Cereals');
insert into category (name) values ('Fast food');


drop table if exists product cascade;
create table product (
id bigserial,
name varchar(255),
category_id bigserial,
price int,
primary key(id),
foreign key(category_id) references category (id) );
insert into product (name, category_id, price) values ('Wine - Saint Emilion Calvet', '1', '25');
insert into product (name, category_id, price) values ('Lemon Balm - Fresh', '2', '11');
insert into product (name, category_id, price) values ('Cookie Dough - Peanut Butter', '4', '23');
insert into product (name, category_id, price) values ('Yukon Jack', '1', '10');
insert into product (name, category_id, price) values ('Carbonated Water - White Grape', '2', '21');
insert into product (name, category_id, price) values ('Oats Large Flake', '11', '16');
insert into product (name, category_id, price) values ('Irish Cream - Baileys', '1', '14');
insert into product (name, category_id, price) values ('Pepper - Pablano', '5', '12');
insert into product (name, category_id, price) values ('Wine - White Cab Sauv.on', '1', '47');
insert into product (name, category_id, price) values ('Wine - Cave Springs Dry Riesling', '1', '46');
insert into product (name, category_id, price) values ('Coffee - Flavoured', '2', '18');
insert into product (name, category_id, price) values ('Silicone Parch. 16.3x24.3', '7', '30');
insert into product (name, category_id, price) values ('Shark - Loin', '9', '15');
insert into product (name, category_id, price) values ('Pastry - Baked Scones - Mini', '4', '34');
insert into product (name, category_id, price) values ('Onions - Green', '5', '28');
insert into product (name, category_id, price) values ('Goulash Seasoning', '6', '18');
insert into product (name, category_id, price) values ('Capers - Ox Eye Daisy', '5', '34');
insert into product (name, category_id, price) values ('Nantuket Peach Orange', '4', '15');
insert into product (name, category_id, price) values ('Soup - Campbells Beef Noodle', '12', '13');
insert into product (name, category_id, price) values ('Rabbit - Legs', '10', '47');
insert into product (name, category_id, price) values ('Mushroom - Enoki, Dry', '5', '43');
insert into product (name, category_id, price) values ('Puree - Blackcurrant', '8', '39');
insert into product (name, category_id, price) values ('Cake - Pancake', '4', '19');
insert into product (name, category_id, price) values ('Filo Dough', '4', '26');
insert into product (name, category_id, price) values ('Liners - Banana, Paper', '4', '15');
insert into product (name, category_id, price) values ('Sage Ground Wiberg', '6', '17');
insert into product (name, category_id, price) values ('Honey - Liquid', '8', '45');
insert into product (name, category_id, price) values ('Olives - Morracan Dired', '5', '11');
insert into product (name, category_id, price) values ('Wine - White, Lindemans Bin 95', '1', '28');
insert into product (name, category_id, price) values ('Flour - Semolina', '11', '11');
insert into product (name, category_id, price) values ('Pumpkin - Seed', '11', '31');
insert into product (name, category_id, price) values ('Chocolate - Milk', '3', '17');
insert into product (name, category_id, price) values ('Chicken - White Meat, No Tender', '10', '27');
insert into product (name, category_id, price) values ('Sea Bass - Fillets', '10', '30');
insert into product (name, category_id, price) values ('Lamb Shoulder Boneless Nz', '10', '46');
insert into product (name, category_id, price) values ('Chicken Breast Wing On', '10', '48');
insert into product (name, category_id, price) values ('Turkey Leg With Drum And Thigh', '10', '19');
insert into product (name, category_id, price) values ('Haggis', '12', '40');
insert into product (name, category_id, price) values ('Wine - Fume Blanc Fetzer', '1', '11');
insert into product (name, category_id, price) values ('Canada Dry', '2', '28');
insert into product (name, category_id, price) values ('Cheese Cloth No 100', '3', '44');
insert into product (name, category_id, price) values ('Cherries - Bing, Canned', '8', '21');
insert into product (name, category_id, price) values ('Sausage - Meat', '10', '26');
insert into product (name, category_id, price) values ('Quail - Jumbo', '10', '13');
insert into product (name, category_id, price) values ('Bread - Corn Muffaleta Onion', '4', '30');
insert into product (name, category_id, price) values ('Petit Baguette', '4', '42');
insert into product (name, category_id, price) values ('Soup - Knorr, Veg / Beef', '12', '11');
insert into product (name, category_id, price) values ('Sproutsmustard Cress', '5', '32');
insert into product (name, category_id, price) values ('Turnip - Wax', '5', '27');
insert into product (name, category_id, price) values ('Potatoes - Yukon Gold, 80 Ct', '5', '38');
insert into product (name, category_id, price) values ('Bacardi Breezer - Strawberry', '1', '19');
insert into product (name, category_id, price) values ('Brandy Cherry - Mcguinness', '1', '45');
insert into product (name, category_id, price) values ('Napkin - Beverge, White 2 - Ply', '1', '45');
insert into product (name, category_id, price) values ('Pork - Back, Short Cut, Boneless', '10', '39');
insert into product (name, category_id, price) values ('Wine - Alicanca Vinho Verde', '1', '44');
insert into product (name, category_id, price) values ('Cake - Box Window 10x10x2.5', '4', '22');
insert into product (name, category_id, price) values ('Spice - Greek 1 Step', '6', '31');
insert into product (name, category_id, price) values ('Napkin - Beverage 1 Ply', '7', '30');
insert into product (name, category_id, price) values ('V8 - Vegetable Cocktail', '2', '42');
insert into product (name, category_id, price) values ('Wine - Cahors Ac 2000, Clos', '1', '16');
insert into product (name, category_id, price) values ('Cheese - Taleggio D.o.p.', '3', '28');
insert into product (name, category_id, price) values ('Ecolab - Ster Bac', '7', '46');
insert into product (name, category_id, price) values ('Pasta - Canelloni, Single Serve', '4', '39');
insert into product (name, category_id, price) values ('Mustard - Individual Pkg', '6', '49');
insert into product (name, category_id, price) values ('Cheese - Montery Jack', '3', '14');
insert into product (name, category_id, price) values ('Pasta - Cappellini, Dry', '4', '28');
insert into product (name, category_id, price) values ('Rice - 7 Grain Blend', '11', '38');
insert into product (name, category_id, price) values ('Wine - Red, Mosaic Zweigelt', '1', '37');
insert into product (name, category_id, price) values ('Gatorade - Xfactor Berry', '2', '14');
insert into product (name, category_id, price) values ('Lemons', '8', '14');
insert into product (name, category_id, price) values ('Bag Stand', '9', '37');
insert into product (name, category_id, price) values ('Flour - So Mix Cake White', '4', '47');
insert into product (name, category_id, price) values ('Cheese - Feta', '3', '37');
insert into product (name, category_id, price) values ('Pork - Ham, Virginia', '10', '20');
insert into product (name, category_id, price) values ('Butter - Salted, Micro', '12', '11');
insert into product (name, category_id, price) values ('Sprouts - Peppercress', '10', '31');
insert into product (name, category_id, price) values ('Leeks - Large', '5', '19');
insert into product (name, category_id, price) values ('Aspic - Amber', '12', '49');
insert into product (name, category_id, price) values ('Shiratamako - Rice Flour', '4', '47');
insert into product (name, category_id, price) values ('Sugar - Brown, Individual', '6', '10');
insert into product (name, category_id, price) values ('Pate - Peppercorn', '10', '40');
insert into product (name, category_id, price) values ('Rice - Wild', '11', '36');
insert into product (name, category_id, price) values ('Cheese - Cream Cheese', '3', '46');
insert into product (name, category_id, price) values ('Asparagus - Green, Fresh', '5', '20');
insert into product (name, category_id, price) values ('Wine - Penfolds Koonuga Hill', '1', '19');
insert into product (name, category_id, price) values ('Quinoa', '11', '32');
insert into product (name, category_id, price) values ('Wine - Red, Mouton Cadet', '1', '21');
insert into product (name, category_id, price) values ('Club Soda - Schweppes, 355 Ml', '2', '38');
insert into product (name, category_id, price) values ('Juice - Mango', '2', '47');
insert into product (name, category_id, price) values ('Truffle Cups - Red', '3', '27');
insert into product (name, category_id, price) values ('Wine - Chardonnay Mondavi', '1', '23');
insert into product (name, category_id, price) values ('Campari', '1', '37');
insert into product (name, category_id, price) values ('Wonton Wrappers', '4', '33');
insert into product (name, category_id, price) values ('Garlic', '5', '16');
insert into product (name, category_id, price) values ('Flour - Bread', '4', '40');
insert into product (name, category_id, price) values ('Parsley Italian - Fresh', '5', '19');
insert into product (name, category_id, price) values ('Steam Pan - Half Size Deep', '7', '32');
insert into product (name, category_id, price) values ('Longan', '8', '20');
insert into product (name, category_id, price) values ('Red Cod Fillets - 225g', '10', '14');
insert into product (name, category_id, price) values ('Noodles - Steamed Chow Mein', '4', '16');