drop table if exists product cascade;
create table product (id bigserial, name varchar(255), price int, primary key(id));
insert into product (name, price) values ('Wine - Saint Emilion Calvet', '25');
insert into product (name, price) values ('Lemon Balm - Fresh', '11');
insert into product (name, price) values ('Cookie Dough - Peanut Butter', '23');
insert into product (name, price) values ('Yukon Jack', '10');
insert into product (name, price) values ('Carbonated Water - White Grape', '21');
insert into product (name, price) values ('Oats Large Flake', '16');
insert into product (name, price) values ('Irish Cream - Baileys', '14');
insert into product (name, price) values ('Pepper - Pablano', '12');
insert into product (name, price) values ('Wine - White Cab Sauv.on', '47');
insert into product (name, price) values ('Wine - Cave Springs Dry Riesling', '46');
insert into product (name, price) values ('Coffee - Flavoured', '18');
insert into product (name, price) values ('Silicone Parch. 16.3x24.3', '30');
insert into product (name, price) values ('Shark - Loin', '15');
insert into product (name, price) values ('Pastry - Baked Scones - Mini', '34');
insert into product (name, price) values ('Onions - Green', '28');
insert into product (name, price) values ('Goulash Seasoning', '18');
insert into product (name, price) values ('Capers - Ox Eye Daisy', '34');
insert into product (name, price) values ('Nantuket Peach Orange', '15');
insert into product (name, price) values ('Soup - Campbells Beef Noodle', '13');
insert into product (name, price) values ('Rabbit - Legs', '47');
insert into product (name, price) values ('Mushroom - Enoki, Dry', '43');
insert into product (name, price) values ('Puree - Blackcurrant', '39');
insert into product (name, price) values ('Cake - Pancake', '19');
insert into product (name, price) values ('Filo Dough', '26');
insert into product (name, price) values ('Liners - Banana, Paper', '15');
insert into product (name, price) values ('Sage Ground Wiberg', '17');
insert into product (name, price) values ('Honey - Liquid', '45');
insert into product (name, price) values ('Olives - Morracan Dired', '11');
insert into product (name, price) values ('Wine - White, Lindemans Bin 95', '28');
insert into product (name, price) values ('Flour - Semolina', '11');
insert into product (name, price) values ('Pumpkin - Seed', '31');
insert into product (name, price) values ('Chocolate - Milk', '17');
insert into product (name, price) values ('Chicken - White Meat, No Tender', '27');
insert into product (name, price) values ('Sea Bass - Fillets', '30');
insert into product (name, price) values ('Lamb Shoulder Boneless Nz', '46');
insert into product (name, price) values ('Chicken Breast Wing On', '48');
insert into product (name, price) values ('Turkey Leg With Drum And Thigh', '19');
insert into product (name, price) values ('Haggis', '40');
insert into product (name, price) values ('Wine - Fume Blanc Fetzer', '11');
insert into product (name, price) values ('Canada Dry', '28');
insert into product (name, price) values ('Cheese Cloth No 100', '44');
insert into product (name, price) values ('Cherries - Bing, Canned', '21');
insert into product (name, price) values ('Sausage - Meat', '26');
insert into product (name, price) values ('Quail - Jumbo', '13');
insert into product (name, price) values ('Bread - Corn Muffaleta Onion', '30');
insert into product (name, price) values ('Petit Baguette', '42');
insert into product (name, price) values ('Soup - Knorr, Veg / Beef', '11');
insert into product (name, price) values ('Sproutsmustard Cress', '32');
insert into product (name, price) values ('Turnip - Wax', '27');
insert into product (name, price) values ('Potatoes - Yukon Gold, 80 Ct', '38');
insert into product (name, price) values ('Bacardi Breezer - Strawberry', '19');
insert into product (name, price) values ('Brandy Cherry - Mcguinness', '45');
insert into product (name, price) values ('Napkin - Beverge, White 2 - Ply', '45');
insert into product (name, price) values ('Pork - Back, Short Cut, Boneless', '39');
insert into product (name, price) values ('Wine - Alicanca Vinho Verde', '44');
insert into product (name, price) values ('Cake - Box Window 10x10x2.5', '22');
insert into product (name, price) values ('Spice - Greek 1 Step', '31');
insert into product (name, price) values ('Napkin - Beverage 1 Ply', '30');
insert into product (name, price) values ('V8 - Vegetable Cocktail', '42');
insert into product (name, price) values ('Wine - Cahors Ac 2000, Clos', '16');
insert into product (name, price) values ('Cheese - Taleggio D.o.p.', '28');
insert into product (name, price) values ('Ecolab - Ster Bac', '46');
insert into product (name, price) values ('Pasta - Canelloni, Single Serve', '39');
insert into product (name, price) values ('Mustard - Individual Pkg', '49');
insert into product (name, price) values ('Cheese - Montery Jack', '14');
insert into product (name, price) values ('Pasta - Cappellini, Dry', '28');
insert into product (name, price) values ('Rice - 7 Grain Blend', '38');
insert into product (name, price) values ('Wine - Red, Mosaic Zweigelt', '37');
insert into product (name, price) values ('Gatorade - Xfactor Berry', '14');
insert into product (name, price) values ('Lemons', '14');
insert into product (name, price) values ('Bag Stand', '37');
insert into product (name, price) values ('Flour - So Mix Cake White', '47');
insert into product (name, price) values ('Cheese - Feta', '37');
insert into product (name, price) values ('Pork - Ham, Virginia', '20');
insert into product (name, price) values ('Butter - Salted, Micro', '11');
insert into product (name, price) values ('Sprouts - Peppercress', '31');
insert into product (name, price) values ('Leeks - Large', '19');
insert into product (name, price) values ('Aspic - Amber', '49');
insert into product (name, price) values ('Shiratamako - Rice Flour', '47');
insert into product (name, price) values ('Sugar - Brown, Individual', '10');
insert into product (name, price) values ('Pate - Peppercorn', '40');
insert into product (name, price) values ('Rice - Wild', '36');
insert into product (name, price) values ('Cheese - Cream Cheese', '46');
insert into product (name, price) values ('Asparagus - Green, Fresh', '20');
insert into product (name, price) values ('Wine - Penfolds Koonuga Hill', '19');
insert into product (name, price) values ('Quinoa', '32');
insert into product (name, price) values ('Wine - Red, Mouton Cadet', '21');
insert into product (name, price) values ('Club Soda - Schweppes, 355 Ml', '38');
insert into product (name, price) values ('Juice - Mango', '47');
insert into product (name, price) values ('Truffle Cups - Red', '27');
insert into product (name, price) values ('Wine - Chardonnay Mondavi', '23');
insert into product (name, price) values ('Campari', '37');
insert into product (name, price) values ('Wonton Wrappers', '33');
insert into product (name, price) values ('Garlic', '16');
insert into product (name, price) values ('Flour - Bread', '40');
insert into product (name, price) values ('Parsley Italian - Fresh', '19');
insert into product (name, price) values ('Steam Pan - Half Size Deep', '32');
insert into product (name, price) values ('Longan', '20');
insert into product (name, price) values ('Red Cod Fillets - 225g', '14');
insert into product (name, price) values ('Noodles - Steamed Chow Mein', '16');